<?php
/**
 * includes/recap-phrases.php
 * Matteo's curated flavor-line bank for weekly recap articles (see
 * includes/weekly-recap.php). ~400 broadcast-style color-commentary
 * lines, organized into the same categories he grouped them in.
 *
 * These are pure flavor, not factual claims -- no line here names a
 * real person tied to a real quote, and none of the play-by-play /
 * crowd / stadium lines are presented as reporting on a specific real
 * event (this league doesn't have a physical stadium or play-by-play
 * data to report on in the first place). rotc_recap_paragraphs() in
 * includes/weekly-recap.php weaves a handful of these in around the
 * real, factual content (actual score, actual top performer, actual
 * bench-miss, actual next opponent) as connective color, the same way
 * a sports-radio broadcast uses hype lines between real play calls.
 *
 * Picks are deterministic (seeded by game+week+slot), so a given
 * matchup shows the same lines on every reload rather than a
 * different random set each time. To add more lines, paste them into
 * the matching category array below.
 */
const ROTC_RECAP_PHRASE_BANK = [
    // Article Openers (5 lines)
    'openers' => [
        'Wham! Bam! Thank you, ma\'am! The pigskin is back in the laboratory, and tonight, the chemistry was volatile!',
        'Live from the big house, under the Friday night lights, where the big boys come to play!',
        'Buckle up, football fans, because we had a real old-fashioned, blue-plate special on the menu today!',
        'They came, they saw, they kicked the physical football machine into overdrive from the opening whistle!',
        'The weather outside was frightful, but the action on the gridiron was absolutely delightful!',
    ],
    // Crowd and Atmosphere (30 lines)
    'crowdAtmosphere' => [
        'The home crowd was rowdy, raucous, and ready to rumble before the referee even blew the whistle!',
        'Noise levels went all the way up to eleven, roaring like a freight train through the upper deck!',
        'Decibel levels were absolutely off the charts, causing a minor seismic event in Section 104!',
        'Tailgaters were cooking up a storm five hours before kickoff, filling the air with the sweet smell of victory!',
        'A sea of team colors covered the bleachers, waving banners like a wild political convention!',
        'The fans stayed glued to their seats despite a sudden downpour that looked like Noah\'s ark part two!',
        'The visiting team’s chant was completely swallowed whole by the hometown faithful!',
        'Thousands of towels were spinning like ceiling fans gone wild during the opening kickoff!',
        'The stadium shook, rattled, and rolled when the defense came up with the first big takeaway!',
        'The student section brought the noise, the energy, and some giant cardboard cutouts that defied logic!',
        'Half the stadium stood up for the entire fourth quarter, refusing to sit down on the job!',
        'The roar of the crowd could be heard all the way down the turnpike!',
        'Fans cheered wildly for a simple warm-up kick like it was the game-winner in the big game!',
        'The wave circled the bowl four times, keeping the folks in the cheap seats properly entertained!',
        'Travel fans occupied a massive block behind the away bench, making a little noise of their own!',
        'The stadium went dead silent, you could hear a pin drop on a mattress, after the whistle blew!',
        'Rowdy fans in the end zone were giving the opponent\'s kicker a piece of their mind and then some!',
        'The attendance numbers broke the record, squeezing every single body into the building!',
        'The home crowd gave a standing ovation that lasted longer than most Hollywood movies!',
        'The stadium announcer had to beg the crowd to lower the volume so the offense could hear the snap!',
        'Alumni players stood on the sidelines, pumping their fists and getting the fans into a frenzy!',
        'Noise meters on the big screen broke into the red early, screaming "Loud" with a capital L!',
        'Kids in the front row got the souvenir of a lifetime when the safety tossed his gloves into the stands!',
        'The energy in the building changed the second they opened up the retractable roof to the elements!',
        'Security lines were long, but the fans didn’t care, they were just hungry for some football!',
        'Diehard fans painted their chests in sub-zero weather, showing a level of dedication that deserves a medal!',
        'The local high school team showed up in their jerseys, cheering on the big boys like future pros!',
        'The crowd stayed loud even when the home team fell behind by two scores, refusing to pack it in!',
        'The end zone bleachers were a hotbed of football fanaticism from the first quarter to the fourth!',
        'The collective gasp from eighty thousand people was loud enough to move the clouds!',
    ],
    // Stadium and Concessions (30 lines)
    'stadiumConcessions' => [
        'The lines for the signature stadium burgers looked like the turnpike on Thanksgiving weekend!',
        'Fans lined up early for the half-price souvenir cups, getting more bang for their football buck!',
        'The new turf looked like a million bucks under the high-intensity stadium bulbs!',
        'Hot coffee sold out by the start of the third quarter, leaving the fans shivering but happy!',
        'The stadium roof slammed shut ten minutes before the national anthem to keep the elements out!',
        'Commemorative programs were flying off the shelves faster than hotcakes on a Sunday morning!',
        'The giant video board showed historical highlights that brought back memories of the good old days!',
        'Local food trucks in the plaza saw massive lines of hungry fans looking for a pre-game snack!',
        'The stadium lights flashed in perfect sync with the team fight song, creating a rock concert vibe!',
        'Cold weather drove thousands into the indoor concourses at halftime for some much-needed shelter!',
        'The team store ran out of home jerseys before kickoff, leaving latecomers out in the cold!',
        'Upgraded Wi-Fi allowed fantasy managers to check their stats at the speed of light!',
        'The stadium organist kept the keys rolling, keeping the old-school football spirit alive!',
        'Free team flags were placed on every single seat, turning the stadium into a waving ocean of color!',
        'The rich aroma of roasted nuts filled the lower level concourse, tempting every fan in sight!',
        'The giant replay screen gave everyone a bird\'s-eye view of the controversial play at the goal line!',
        'Hot chocolate vendors ran completely out of milk before the first half even came to a close!',
        'The stadium crew cleared the field of snow in record time, working like an well-oiled machine!',
        'Luxury suites were packed with local bigwigs, former greats, and Hollywood stars!',
        'High parking fees did not deter a massive turnout that filled the south lot to maximum capacity!',
        'The stadium sound system blasted heavy rock music, getting the defensive huddle properly jacked up!',
        'Brand new ribbon boards tracked individual player stats, giving the fantasy gurus everything they needed!',
        'The halftime show featured the local youth league, putting on a show that warmed the heart!',
        'Gates opened three hours early to accommodate the massive, surging wave of humanity!',
        'Elevators to the upper deck experienced long delays, but nobody was complaining on football Sunday!',
        'The stadium security team managed the massive entry lines with precision and a smile!',
        'The stadium lights dimmed dramatically for introductions, turning the tunnel into a rock stage!',
        'Clear blue skies made for a picture-perfect afternoon of old-fashioned gridiron action!',
        'The merchandise stands saw a massive surge in sales for the thick winter beanies!',
        'The stadium field goal nets stayed busy all afternoon, getting a workout from both kickers!',
    ],
    // Player Names and Pre-game Puns (30 lines)
    'playerPuns' => [
        'Mike "Tuck and" Roll arrived early, looking focused and ready to move the chains!',
        'Chris "The Kitchen" Sink was seen working on his pass rush moves during early warmups!',
        'Billy "Don\'t Go" Bacon was sizzling on the turf, running routes with maximum flavor!',
        'Ray "In the" Woods spent twenty minutes pacing the field alone, getting his mind right!',
        'Tom "The Cat" Burglar was practicing his interception returns, looking to steal one tonight!',
        'Sam "The Man" Plan was reviewing the playbook on his tablet, looking for the winning formula!',
        'Dan "The Man" Can was throwing darts in the end zone, looking sharp from fifteen yards out!',
        'Joe "The Toe" Morrow was booming kicks into the upper deck during the early specialist warmups!',
        'The starting quarterback arrived looking like a million bucks in a custom three-piece suit!',
        'Rookies were out on the field early, taking photos of the empty stadium to send back home to mom!',
        'The team captain gave an intense, fire-and-brimstone speech in the tunnel before heading out!',
        'Trainers worked diligently on the starting cornerback\'s ankle, trying to tape it up for the big game!',
        'Players interacted with the fans near the tunnel, signing autographs and spreading the football love!',
        'The medical staff checked the turf density, making sure the surface was safe for the speedsters!',
        'The starting safety ran through the tunnel waving a giant team flag, getting the crowd jacked up!',
        'Specialists checked the wind direction by tossing grass into the air like old-school meteorologists!',
        'The visiting team took a group photo at midfield, trying to capture the moment before the battle!',
        'Coaches gathered in the end zone, looking over the final script like Hollywood directors!',
        'The punter worked on his directional kicks, trying to find the coffin corner all afternoon!',
        'Team captains met at midfield for an early chat with the stripes, setting the ground rules!',
        'Media members crowded around the star receiver, looking for that million-dollar quote!',
        'The backup offensive line practiced their short snaps, ready to step in at a moment\'s notice!',
        'Players wore custom warm-up shirts, supporting a local cause and showing some big-time heart!',
        'The head coach stood by the tunnel, high-fiving every single player like a proud father!',
        'The starting edge rusher ran a lap around the entire field alone, getting his engine revved up!',
        'Physical therapists stretched out the tight ends, making sure the big targets were flexible!',
        'The quarterback checked his helmet communication system, making sure the line to the booth was crystal clear!',
        'Players used resistance bands near the bench, getting the muscles firing before the real hitting started!',
        'The kick returner practiced tracking high punts in the sun, making sure his eyes were adjusted!',
        'Team staff set up the big cooling fans along the bench, bracing for a hot afternoon in the trenches!',
    ],
    // Game Play and Tackles (30 lines)
    'gamePlay' => [
        'He drops back, looks, and biff! The middle linebacker leveled him at the line of scrimmage!',
        'He’s running, he’s passing, he’s... tick, tick, tick... boom! Safety help arrived just in time!',
        'The defensive line held firm on fourth-and-one like a concrete wall at the goal line!',
        'He jumped the route, he had it, he dropped it! Oh, doctor, he’s going to want that one back!',
        'The running back bounced off three tackles, rumbling, bumbling, and stumbling for the first down!',
        'The offensive line opened a hole so wide you could have driven a semi-truck right through it!',
        'The defensive tackle pushed the center three yards into the backfield, completely blowing up the play!',
        'The punter boomed it high, boomed it deep, and pinned them inside the five-yard line! Beautiful!',
        'The quarterback stood tall in the pocket and delivered a strike right before getting his clock cleaned!',
        'The receiver held onto the pigskin despite taking a ferocious hit across the middle! Talk about tough!',
        'The pass rush came screaming off the edge, forcing an intentional grounding penalty that killed the drive!',
        'The kicker sneaked the ball inside the right upright by the absolute hair on his chinny-chin-chin!',
        'The defense read the screen play perfectly, swarming the backfield like a pack of wild dogs!',
        'The cornerback used his leverage to force the receiver out of bounds before he could make the catch!',
        'The running back used a vicious stiff arm to gain five extra yards and send a message!',
        'The edge rusher blew past the tackle like he was standing still for a quick sack! Whoosh!',
        'The free safety read the quarterback\'s eyes perfectly and came away with an easy pick-six opportunity!',
        'The offensive tackle committed a costly holding penalty that completely stalled a promising drive!',
        'The defensive end used his long arms to bat the ball down right at the line of scrimmage! No dice!',
        'The kicker booted the ball through the back of the end zone, giving the return man a rest!',
        'The receiver ran a crisp, clean route to create five yards of separation from his defender!',
        'The quarterback used his legs, tucked the ball, and picked up a crucial first down on the ground!',
        'The defensive line stayed disciplined during the trick play, refusing to bite on the fake!',
        'The fullback cleared the path, laying a block that allowed the runner to cruise into the end zone!',
        'The safety made a touchdown-saving tackle along the sideline, saving six points at the last second!',
        'The defensive line brought heavy pressure up the middle, making life miserable for the passer!',
        'The pass hit the receiver right in the numbers for a first down that moved the chains!',
        'The cornerback got called for pass interference on the deep ball, a costly mistake for the defense!',
        'The running back found a lane, hit the turbo button, and gained twenty yards on the ground!',
        'The defense came out smoking, forcing a quick three-and-out on the game\'s opening possession!',
    ],
    // Key Plays and Shifts (30 lines)
    'keyPlays' => [
        'A fumbled snap turned the tide of the game completely around in the third quarter!',
        'The blocked punt put the home team in perfect scoring position, turning the stadium into a madhouse!',
        'A fifty-yard completion flipped the field entirely, changing the geography of the gridiron!',
        'The replay review overturned a crucial touchdown catch, leaving the home fans completely furious!',
        'An interception in the red zone ended a promising drive and broke the offense\'s back!',
        'The successful fake punt caught the defense completely napping, a brilliant call by the coaching staff!',
        'A roughing the passer penalty kept the drive alive for the away team, a real gift from the stripes!',
        'The running back broke free, made one man miss, and went sixty yards for a touchdown! See ya!',
        'A strip-sack put the defense on the scoreboard with a scoop-and-score that electrified the building!',
        'The offense converted a third-and-fifteen with a screen pass that execution-wise was flawless!',
        'A missed field goal gave the opposing team great field position and a new lease on life!',
        'The defense stuffed the quarterback sneak on fourth down, holding the line with brute force!',
        'A kickoff return for a touchdown sent the stadium into an absolute frenzy of flying beer and cheers!',
        'The receiver made a spectacular, circus-style, one-handed catch along the sideline that you have to see to believe!',
        'A defensive holding call gave the offense a fresh set of downs when they were completely dead in the water!',
        'The quarterback threw a perfect back-shoulder pass for a score, putting it where only his man could get it!',
        'A penalty for twelve men on the field ruined a great defensive stop, a real mental error there!',
        'The safety forced a fumble just before the runner crossed the goal line, a spectacular defensive play!',
        'The offense used a flea-flicker play to gain forty yards, pulling an old trick out of the bag!',
        'A sideline catch was upheld after a lengthy video review that had everyone holding their breath!',
        'The defense recovered a loose ball on the opening kickoff of the half, starting things off with a bang!',
        'A short pass turned into a massive gain after three missed tackles along the sideline! Unbelievable!',
        'The quarterback threw an interception on his very first pass of the day, a nightmare start for him!',
        'A crucial drop on third down forced the team to punt, a real drive-killer for the offense!',
        'The kicker made a career-long field goal to end the half, booting it from the next county!',
        'The defense forced three consecutive turnovers in the second half, completely taking over the football game!',
        'A double pass trick play resulted in a wide-open touchdown that fooled everyone in the stadium!',
        'The running back converted a fourth-down attempt by the absolute nose of the football!',
        'A defensive pass interference call put the ball on the one-yard line, setting up an easy score!',
        'The quarterback threw a game-winning touchdown pass with ten seconds left, a legendary finish to a great game!',
    ],
    // Fan Engagement (30 lines)
    'fanEngagement' => [
        'Fans participated in a stadium-wide light show using their phones, turning the arena into a galaxy!',
        'The dance cam featured a fan in a full team uniform who was absolutely shaking what his mama gave him!',
        'Kids competed in a field goal kicking contest at halftime, showing some real leg talent out there!',
        'Fans cheered as the military flyover passed above the stadium, a truly goosebump-inducing moment!',
        'The loudest section won free pizza during the third quarter, causing a screaming match in the upper deck!',
        'Fans caught t-shirts launched from cannons on the field, diving over seats like they were loose balls!',
        'A lucky fan won a new truck by hitting the crossbar from thirty yards out! Give that man a contract!',
        'The crowd sang along to a classic rock anthem during the timeout, a giant stadium-wide karaoke session!',
        'Young fans lined up to high-five the team mascot in the plaza, making memories that will last a lifetime!',
        'The stadium video board showed marriage proposals during halftime, love was definitely in the football air!',
        'Fans participated in a trivia contest on the big screen, testing their knowledge of team history!',
        'The crowd gave a thundering standing ovation to a military veteran on the field, a class act by everyone!',
        'Fans chanted the name of the backup quarterback after a big play, showing some love for the number two guy!',
        'The team mascot ran across the field with a giant team flag, keeping the energy levels at an all-time high!',
        'Fans wore matching shirts to create a stadium-wide color pattern that looked incredible from the Goodyear blimp!',
        'The crowd stayed engaged by booing the referees after a tough call, letting the stripes know how they felt!',
        'Fans took photos with old championship trophies in the concourse, reliving the glory days of yesteryear!',
        'The video board highlighted the best fan costumes of the night, including a guy dressed as a giant hot dog!',
        'Fans participated in a loud call-and-response chant led by the stadium announcer that shook the windows!',
        'The crowd erupted when a lucky fan caught a stray field goal ball in the upper deck! Keep it!',
        'Fans voted for the player of the game on their mobile apps, letting their voices be heard digitally!',
        'The stadium host interviewed fans in the stands during timeouts, finding some real colorful characters out there!',
        'Fans wore custom hats shaped like the team logo, showing off some serious football fashion!',
        'The crowd held up signs supporting the injured star player, showing that this fanbase is one big family!',
        'Fans participated in a noise competition between the east and west stands, a real battle of the lungs!',
        'The stadium staff handed out glowing wristbands to all attendees, turning the stadium into a neon dream!',
        'Fans lined the streets to cheer for the team bus after the win, giving the boys a hero\'s send-off!',
        'The pre-game tailgate scene was an absolute carnival of football, food, and fun!',
        'Fans were doing the twist in the aisles after the home team scored three straight touchdowns!',
        'The stadium energy was so high you could have used it to power the entire city for a week!',
    ],
    // Generic Details for Random Scenarios (30 lines)
    'genericDetails' => [
        'The referee had to explain a complex rule over the microphone, looking like a law professor out there!',
        'The chain gang moved quickly to measure a close first down, bringing out the old-school chains!',
        'Coaches spent the timeout drawing up a new play on the tablet, looking for a weakness in the armor!',
        'The ball bounced off the turf and took a strange, erratic hop out of bounds like a frightened rabbit!',
        'The medical tent saw action early as players dealt with muscle cramps in the sweltering heat!',
        'The backup punter stood on the sideline ready to enter the game, practicing his drops just in case!',
        'Rain began to fall heavily right at the start of the second half, turning the field into a slip-and-slide!',
        'The wind kept blowing the ball off the kicking tee, forcing the holder to get a finger on it early!',
        'The turf became slick as the temperature dropped rapidly, making footing a real guessing game!',
        'Both teams gathered at midfield for a brief post-game handshake, showing some real sportsmanship!',
        'The head coach used his final challenge flag of the half, throwing the red bean with authority!',
        'The quarterback changed the play at the line of scrimmage, barking out the audibles like a drill sergeant!',
        'The defense switched to a zone coverage scheme in the second half to slow down the passing attack!',
        'Shadows stretched across the field during the late afternoon game, making visibility a real challenge!',
        'The official review took five long minutes to determine the exact spot of the football!',
        'Trainers applied ice to the starting defensive end\'s shoulder, trying to keep the big man in the game!',
        'The offense ran a hurry-up style to prevent defensive substitutions and keep the pressure on!',
        'The ball marks on the turf showed exactly where the runner stepped out of bounds by a fraction of an inch!',
        'The defensive coordinator moved from the press box to the sideline to get a better feel for the game!',
        'The team equipment staff quickly changed a player\'s broken cleats, working with pit-crew speed!',
        'The quarterback used a clever hard count to draw the defense offsides on third-and-short! Got \'em!',
        'The punter had to kick out of his own end zone under heavy, screaming pressure from the rush!',
        'The referee dropped his flag immediately after the snap, spotting an illegal formation from the get-go!',
        'The ball slipped out of the quarterback\'s hand during a pass attempt, resulting in a comical duck!',
        'The defense packed the box with eight men to stop the expected running play on first down!',
        'The offense used all three of their timeouts early in the second half, a move that could haunt them later!',
        'The kicking team recovered their own onside kick attempt, a perfectly executed trick that shocked everyone!',
        'The stadium clock operator experienced a brief technical issue, causing a minor delay on the field!',
        'The head coach looked absolutely furious on the sideline after a costly unsportsmanlike penalty!',
        'The players used the heated benches to stay warm between series, bundled up like Eskimos out there!',
    ],
    // Additional Game Action (30 lines)
    'additionalGameAction' => [
        'He goes deep, he leaps, and knock-down! The defensive back batted the ball away in the nick of time!',
        'A short pass over the middle picked up the necessary yardage to keep the drive moving forward!',
        'The running back found a crease, hit the line, and gained twelve quick yards before anyone noticed!',
        'The defensive line stopped the runner cold behind the line of scrimmage, an absolute stone-cold stop!',
        'The quarterback delivered a beautiful deep ball right into the bread basket of his wide receiver!',
        'The kickoff went deep into the end zone for a touchback, giving the defense a chance to rest!',
        'The safety made a fantastic open-field tackle to prevent a massive gain on the trick play!',
        'The offensive line provided a clean, pristine pocket for the quarterback to operate all afternoon!',
        'The cornerback stayed glued to the receiver throughout the entire route, like white on rice!',
        'The defensive tackle collapsed the pocket from the inside, forcing an awkward throw from the passer!',
        'The punter boomed a high, hanging kick that forced a fair catch at the ten-yard line!',
        'The kicker nailed a forty-five-yard field goal with plenty of leg room to spare! Right down the middle!',
        'The running back picked up the blitzing linebacker perfectly, giving his quarterback time to throw!',
        'The receiver made a tough, gritty catch while taking a ferocious hit over the middle of the field!',
        'The defense forced an incomplete pass on third-and-long, bringing out the punting unit once again!',
        'The quarterback scrambled out of bounds after a five-yard gain, smart play to avoid the hit!',
        'The defensive end chased the quarterback out of the pocket, forcing him to throw it away!',
        'The offensive tackle sealed the edge beautifully for a highly successful sweep play to the right!',
        'The cornerback read the screen pass perfectly and made the tackle for a loss of four yards!',
        'The safety dropped down into the box, acting like an extra linebacker to stop the running game!',
        'The pass rush got home again, forcing an intentional grounding penalty that cost them a down!',
        'The receiver dropped a well-thrown ball on the sideline, a mistake that had his coach steaming!',
        'The running back dove over the pile for a first down, showing some real goal-line grit!',
        'The defensive line stayed disciplined against the option play, playing assignment football to perfection!',
        'The quarterback completed five consecutive passes on the drive, looking like an All-Pro out there!',
        'The kicker pushed the field goal attempt wide left, a costly miss that left him hanging his head!',
        'The defensive back broke up the pass with a clean, hard hit that dislodged the football!',
        'The offensive line committed a false start penalty on third down, a real mental error in a big spot!',
        'The running back gained five yards on a tough, grinding inside run through the teeth of the defense!',
        'The defense forced a quick punt after three plays, completely dominating the opening minutes of the half!',
    ],
    // Additional Environment and Details (30 lines)
    'environmentDetails' => [
        'Thick fog rolled over the stadium walls during the fourth quarter, making it look like a ghost town!',
        'The temperature dropped ten degrees over the course of the game, turning the field into an ice box!',
        'Flakes of snow began to fall during player introductions, adding some serious drama to the atmosphere!',
        'The stadium seats remained completely full despite the blowout score, shout out to the true fans!',
        'The home team wore their alternate throwback uniforms tonight, looking sharp in the old-school colors!',
        'The visiting team struggled with the high altitude early on, sucking wind on the sidelines!',
        'The stadium lights created a blinding glare on the wet turf after the brief afternoon shower!',
        'Fans used cardboard boxes to keep their feet off the freezing concrete stands! Smart football move!',
        'The wind gusts shifted from west to east during halftime, throwing a wrench into the kicking game!',
        'The setting sun sat directly in the eyes of the deep safety, making high passes a real adventure!',
        'The stadium grass showed significant wear down the middle of the field after four quarters of pounding!',
        'The team benches were crowded with injured players in street clothes, looking like a hospital ward!',
        'The stadium cameras captured the owner watching anxiously from his luxury box high above the field!',
        'The referee\'s microphone cut out during a penalty announcement, leading to some comical hand signals!',
        'The sideline heaters were turned on high for both teams, looking like giant red furnaces out there!',
        'The stadium crew replaced a section of torn turf during the halftime intermission, working fast!',
        'The visiting fans made their presence known during the quiet moments, making some serious noise!',
        'The stadium scoreboard malfunctioned briefly in the third quarter, leaving everyone guessing on the time!',
        'The game ball had to be swapped out frequently due to the mud, keeping the equipment guys busy!',
        'The stadium announcer thanked the fans for another sold-out season of exciting football action!',
        'The chain gang had to use a backup marker after a sideline collision wiped out the original!',
        'The team mascot interacted with the stadium security staff, putting on a funny little show for the fans!',
        'The pre-game music featured big hits from the home city\'s top artists, getting the crowd jacked up!',
        'The stadium gates closed promptly thirty minutes after kickoff to ensure safety for everyone inside!',
        'The media room was packed to the gills with reporters before the game even got underway!',
        'The stadium roof remained half-open due to the unpredictable, changing weather conditions outside!',
        'The medical staff kept a close eye on the players in the extreme, sweltering summer heat!',
        'The stadium concession stands lowered prices for the final quarter, a nice treat for the folks who stayed!',
        'The post-game traffic began building up outside the stadium early, a real nightmare on the highways!',
        'The stadium cleanup crew stood ready in the tunnels long before the final whistle blew!',
    ],
    // Deep Cut Puns and Player Catchphrases (30 lines)
    'deepCutPuns' => [
        'Eric "The Red" met a wall of defenders on that rushing attempt!',
        'Mark "The Spark" provided the energy the offense desperately needed!',
        'He was running like he heard the police sirens behind him!',
        'Greg "The Leg" put his boot to the leather and sent it into orbit!',
        'He was back pedaling faster than a politician after an election!',
        'John "The Baptist" was delivering some serious hits out there today!',
        'He caught the ball and went whoop! Made two men miss in the open field!',
        'The defensive back was playing like he had sticky glue on his gloves!',
        'He threw a pass that looked like a wounded duck flying into a headwind!',
        'The running back hit the hole like a cannonball fired from a battleship!',
        'He was rumbling, bumbling, stumbling all the way to the house!',
        'The linebacker came through the gap like a runaway freight train!',
        'He made a catch that was absolutely spectacular with a capital S!',
        'The quarterback stood in the pocket, cool as the other side of the pillow!',
        'He hit him so hard his ancestors felt it in the next century!',
        'The safety came downhill like an avalanche on a snowy mountain!',
        'He put a move on the cornerback that left him looking for his shoes!',
        'The offensive line was blocking like a row of concrete telephone poles!',
        'He caught the ball and went zoom! Nobody was going to catch him tonight!',
        'The kicker put it through the uprights, clean as a whistle!',
        'He was playing football like a man possessed out there today!',
        'The defense came up big, slamming the door shut on the comeback attempt!',
        'He threw a laser beam right into the tightest window imaginable!',
        'The running back was running with a purpose and a lot of bad intentions!',
        'He made a tackle that was a textbook definition of old-school football!',
        'The quarterback scrambled out of trouble like a magician escaping a straightjacket!',
        'He caught the ball on the sideline, toe-tapping like a ballerina!',
        'The pass rush came screaming in, forcing a hurried throw that went nowhere!',
        'He took the kickoff and found an absolute highway down the middle of the field!',
        'The defense was flying to the football like iron filings to a magnet!',
    ],
    // More Game Action and Strategy (30 lines)
    'moreGameAction' => [
        'The offense came out in a five-wide set, signaling their intentions early!',
        'The defense countered with a dime package to protect against the deep pass!',
        'The running back took the handoff and picked up four tough yards into the teeth of the line!',
        'The quarterback used a quick three-step drop and fired a strike to the tight end!',
        'The cornerback got a hand on the ball, breaking up the pass at the last second!',
        'The punter hit a high hang-time kick that allowed the coverage team to swarm the returner!',
        'The kicker nailed a short thirty-yarder to get the team on the scoreboard!',
        'The offensive line did a fantastic job of picking up the complex safety blitz!',
        'The receiver made a tough catch over the middle, holding on despite the heavy contact!',
        'The defensive tackle got a great push, resetting the line of scrimmage in the backfield!',
        'The quarterback scrambled to his right, looking for an open man downfield!',
        'The running back hit the edge, using his speed to pick up the first down!',
        'The defense line stayed disciplined, refusing to give up the cutback lane to the runner!',
        'The cornerback played soft coverage, giving up the short completion but preventing the big play!',
        'The pass hit the receiver right in stride, allowing him to pick up yards after the catch!',
        'The defensive end used a spin move to get past the tackle and pressure the quarterback!',
        'The safety played deep center field, keeping everything underneath him all game long!',
        'The offense ran a beautiful play-action fake that completely fooled the linebackers!',
        'The kicker booted it deep into the end zone, forcing another touchback for the defense!',
        'The running back showed great patience, waiting for his blocks to develop before hitting the hole!',
        'The defense forced another incomplete pass, bringing up a critical fourth-down decision!',
        'The quarterback threw a beautiful touch pass over the linebacker\'s head for a big gain!',
        'The receiver ran a double move, completely shaking his defender along the sideline!',
        'The offensive line established their dominance early, running the ball effectively on the opening drive!',
        'The defensive tackle occupied two blockers, freeing up the linebacker to make the tackle!',
        'The quarterback checked down to his running back, picking up a safe five yards on first down!',
        'The cornerback made a great open-field tackle, stopping the receiver short of the first-down marker!',
        'The pass rush forced the quarterback to flush out of the pocket and throw on the run!',
        'The running back used his vision to find an opening on the backside of the play!',
        'The defense stood tall once again, forcing a long field goal attempt from the offense!',
    ],
    // Additional Fan and Stadium Energy (30 lines)
    'fanStadiumEnergy' => [
        'The stadium security staff had their hands full with a couple of rowdy fans in the lower bowl!',
        'The halftime show featured a performance by a popular local marching band that brought down the house!',
        'Fans in the luxury boxes were enjoying the game in style, sipping champagne and eating shrimp!',
        'The stadium video board played a hilarious comedy sketch featuring the team\'s star defensive players!',
        'Young fans were thrilled to receive free team hats as they entered the stadium gates!',
        'The crowd stayed loud and proud throughout the entire game, proving why they are the best fans in the league!',
        'Fans took to social media to share their excitement, causing the team name to trend nationwide!',
        'The stadium atmosphere was truly electric, a perfect night for some high-stakes football!',
        'The team mascot did a spectacular flip on the field, getting a massive cheer from the crowd!',
        'Fans in the end zone section held up giant cards to spell out the team name during a timeout!',
        'The stadium concessions reported record sales of hot dogs and nachos during the first half alone!',
        'The pre-game tailgating scene was filled with music, laughter, and some incredible barbecue!',
        'Fans cheered wildly as the team took the field, creating a deafening roar that shook the stadium!',
        'The stadium lights created a beautiful spectacle, flashing in rhythm with the music during breaks!',
        'The crowd gave a warm welcome to a group of local charity workers who were honored on the field!',
        'Fans wore matching team jerseys, turning the entire stadium into a sea of official team colors!',
        'The stadium announcer kept the crowd informed and entertained with his witty commentary all night long!',
        'Kids in the stands were hopping up and down with excitement every time the team made a big play!',
        'The stadium video board captured some fantastic fan reactions that had everyone laughing out loud!',
        'Fans stayed long after the final whistle, celebrating the big win with their fellow football faithful!',
        'The stadium gates opened early to ensure everyone could find their seats before the opening kickoff!',
        'The pre-game radio show broadcasted live from the stadium plaza, attracting a huge crowd of listeners!',
        'Fans lined up to buy the official game-day program, a great souvenir to remember an incredible matchup!',
        'The stadium atmosphere was family-friendly, with plenty of activities for young fans in the concourse!',
        'The crowd erupted in a spontaneous chant of the team\'s victory song after a spectacular touchdown!',
        'Fans showed off their creative side with some amazing homemade signs supporting their favorite players!',
        'The stadium bowl looked absolutely stunning under the lights, a classic setting for a classic game!',
        'The energy in the building was contagious, with even the casual fans getting into the football spirit!',
        'Fans cheered as the team captains shook hands at midfield, a great display of mutual respect!',
        'The stadium stood as one to applaud the hard work of the stadium crew during the weather delay!',
    ],
    // Final Game Elements (30 lines)
    'finalElements' => [
        'The referee called a tight game, keeping both teams on their best behavior throughout!',
        'The chain gang did an excellent job, moving up and down the sideline with speed and precision!',
        'Coaches used the halftime break to make some crucial adjustments to their game plans!',
        'The football took a lucky bounce for the home team, staying in bounds on a critical punt return!',
        'The medical staff provided excellent care to a player who suffered a minor injury during the play!',
        'The backup quarterback stayed warm on the sideline, throwing passes to the equipment staff!',
        'The weather remained perfect for football, with clear skies and a gentle breeze blowing across the field!',
        'The wind had a minor impact on the passing game, forcing both quarterbacks to throw with more velocity!',
        'The turf provided excellent traction for the players, allowing for some sharp cuts and fast running!',
        'Both teams showed great respect for each other, chatting amiably on the field after the final whistle!',
        'The head coach used his challenges wisely, helping to ensure the correct calls were made on the field!',
        'The quarterback\'s audibles were effective, helping the offense to find the right play against the defense!',
        'The defense\'s zone coverage was tough to crack, forcing the offense to rely on short, patient passes!',
        'The late afternoon sun added a beautiful golden hue to the field during the early quarters of the game!',
        'The official review process was quick and efficient, keeping the game moving along at a good pace!',
        'The trainers worked hard to keep the players hydrated and ready to perform at their absolute best!',
        'The offense\'s hurry-up tempo put the defense on its heels, leading to some big gains on the drive!',
        'The field markers were clear and visible, helping the players and officials to spot the ball accurately!',
        'The defensive coordinator\'s move to the sideline paid off, allowing for better communication with the players!',
        'The equipment staff\'s quick work ensured that no player missed a snap due to a uniform issue!',
        'The quarterback\'s hard count was a valuable weapon, helping to keep the defense off-balance all night!',
        'The punter\'s ability to kick under pressure was crucial, helping to flip the field in tight situations!',
        'The referee\'s quick whistle prevented any unnecessary roughness after the play was clearly dead!',
        'The quarterback\'s ball handling was superb, executing several tricky fakes that fooled the defense!',
        'The defense\'s aggressive front line made it difficult for the offense to establish a consistent running game!',
        'The offense\'s use of timeouts was strategic, saving them for the critical final minutes of the game!',
        'The onside kick attempt was a bold move that showed the coaching staff\'s willingness to take big risks!',
        'The stadium clock was accurate and reliable, ensuring that the game ended without any timing controversy!',
        'The head coach\'s passion was evident on the sideline, inspiring his players to give everything they had!',
        'The players\' use of the heated benches was a smart way to stay warm and prevent injuries in the cold!',
    ],
    // Article Closers (5 lines)
    'closers' => [
        'The curtain comes down, the lights are turning off, and this one is officially in the history books!',
        'He drops the mic, the clock hits all zeros, and that is a wrap from a wild night of football action!',
        'They came, they played, they conquered, and one team walks away with the ultimate prize tonight!',
        'Fans are heading to the turnpike, singing the victory song after a game that had absolutely everything!',
        'The final whistle blows on a masterpiece of gridiron theatre, and we will see you next week, football fans!',
    ],
];

